### ISSUE TITLE
CourseService#ImportCourse does not fail gracefully

### ISSUE THREAD

**Issue by telnicky** [instructure/scorm-cloud#7]
Received unclear exception when course import failed. Looks like we are expecting '//rsp/importresult' to always be present in the response however it may not be when a failure occurs.

Here it the exception that was raised:
`NoMethodError: undefined method 'attributes' for nil:NilClass`

Here is the full response that was getting returned:
```
<?xml version='1.0' encoding='UTF-8'?>
<rsp stat='fail'>
	<err code='2' msg='File upload caused an internal IO error: No space left on device'/>
</rsp>
```

I may follow this up with a PR if I get time, mainly just wanted to make sure this was documented somewhere first.

**Comment by miquella** [comment]
Looks like this should be addressed by #8
